site_name: Catlin Gabel Engineering Handbook
nav:
  - Home: index.md
  - About: about.md
  - Engineering: engineering/index.md
  - Fabrication: fabrication/index.md
  - Design: design/index.md
  - Application Software: appsw/index.md
  - Robot Software: robotsw/index.md
  - Electronics: electronics/index.md
  - Strategy: strategy/index.md
theme: 
  name: material 
  palette: 
    scheme: slate



markdown_extensions:
  - abbr
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.blocks.details
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
