site_name: Catlin Gabel Engineering Compendium
nav:
  - Home: index.md
  - About: about.md
  - Engineering: 
    - engineering/index.md
    - Engineering Process: engineering/engineering_process.md
    - Development Methodologies: engineering/methodologies.md
  - Fabrication: fabrication/index.md
  - Design: design/index.md
  - Software Engineering: software/index.md
  - Application Software: appsw/index.md
  - Robot Software: robotsw/index.md
  - Electronics: electronics/index.md
  - Media: media/index.md
  - Strategy: strategy/index.md
  - Misc:
    - Internships: misc/internships.md

theme: 
  name: material 
  palette: 
    scheme: slate
  logo: img/cg_logo.svg
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: material/information
      tip: fontawesome/solid/fire
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - navigation.instant
    - navigation.path
    - navigation.indexes
    - toc.integrate

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.blocks.caption
  - pymdownx.snippets:
      auto_append:
        - includes/glossary.md
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
